// Generated by gencpp from file fake_sensor/Detect_fiducialRequest.msg
// DO NOT EDIT!


#ifndef FAKE_SENSOR_MESSAGE_DETECT_FIDUCIALREQUEST_H
#define FAKE_SENSOR_MESSAGE_DETECT_FIDUCIALREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace fake_sensor
{
template <class ContainerAllocator>
struct Detect_fiducialRequest_
{
  typedef Detect_fiducialRequest_<ContainerAllocator> Type;

  Detect_fiducialRequest_()
    {
    }
  Detect_fiducialRequest_(const ContainerAllocator& _alloc)
    {
    }






  typedef boost::shared_ptr< ::fake_sensor::Detect_fiducialRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::fake_sensor::Detect_fiducialRequest_<ContainerAllocator> const> ConstPtr;

}; // struct Detect_fiducialRequest_

typedef ::fake_sensor::Detect_fiducialRequest_<std::allocator<void> > Detect_fiducialRequest;

typedef boost::shared_ptr< ::fake_sensor::Detect_fiducialRequest > Detect_fiducialRequestPtr;
typedef boost::shared_ptr< ::fake_sensor::Detect_fiducialRequest const> Detect_fiducialRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::fake_sensor::Detect_fiducialRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::fake_sensor::Detect_fiducialRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace fake_sensor

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'fake_sensor': ['/home/lyoder/Desktop/sandbox/src/fake_sensor/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::fake_sensor::Detect_fiducialRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::fake_sensor::Detect_fiducialRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::fake_sensor::Detect_fiducialRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::fake_sensor::Detect_fiducialRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::fake_sensor::Detect_fiducialRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::fake_sensor::Detect_fiducialRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::fake_sensor::Detect_fiducialRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::fake_sensor::Detect_fiducialRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::fake_sensor::Detect_fiducialRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "fake_sensor/Detect_fiducialRequest";
  }

  static const char* value(const ::fake_sensor::Detect_fiducialRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::fake_sensor::Detect_fiducialRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n\
\n\
";
  }

  static const char* value(const ::fake_sensor::Detect_fiducialRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::fake_sensor::Detect_fiducialRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream&, T)
    {}

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct Detect_fiducialRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::fake_sensor::Detect_fiducialRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream&, const std::string&, const ::fake_sensor::Detect_fiducialRequest_<ContainerAllocator>&)
  {}
};

} // namespace message_operations
} // namespace ros

#endif // FAKE_SENSOR_MESSAGE_DETECT_FIDUCIALREQUEST_H
