// Generated by gencpp from file fake_sensor/Detect_fruit.msg
// DO NOT EDIT!


#ifndef FAKE_SENSOR_MESSAGE_DETECT_FRUIT_H
#define FAKE_SENSOR_MESSAGE_DETECT_FRUIT_H

#include <ros/service_traits.h>


#include <fake_sensor/Detect_fruitRequest.h>
#include <fake_sensor/Detect_fruitResponse.h>


namespace fake_sensor
{

struct Detect_fruit
{

typedef Detect_fruitRequest Request;
typedef Detect_fruitResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Detect_fruit
} // namespace fake_sensor


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::fake_sensor::Detect_fruit > {
  static const char* value()
  {
    return "686cf6b37dc9c7b7e6b340f1d32ac529";
  }

  static const char* value(const ::fake_sensor::Detect_fruit&) { return value(); }
};

template<>
struct DataType< ::fake_sensor::Detect_fruit > {
  static const char* value()
  {
    return "fake_sensor/Detect_fruit";
  }

  static const char* value(const ::fake_sensor::Detect_fruit&) { return value(); }
};


// service_traits::MD5Sum< ::fake_sensor::Detect_fruitRequest> should match 
// service_traits::MD5Sum< ::fake_sensor::Detect_fruit > 
template<>
struct MD5Sum< ::fake_sensor::Detect_fruitRequest>
{
  static const char* value()
  {
    return MD5Sum< ::fake_sensor::Detect_fruit >::value();
  }
  static const char* value(const ::fake_sensor::Detect_fruitRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::fake_sensor::Detect_fruitRequest> should match 
// service_traits::DataType< ::fake_sensor::Detect_fruit > 
template<>
struct DataType< ::fake_sensor::Detect_fruitRequest>
{
  static const char* value()
  {
    return DataType< ::fake_sensor::Detect_fruit >::value();
  }
  static const char* value(const ::fake_sensor::Detect_fruitRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::fake_sensor::Detect_fruitResponse> should match 
// service_traits::MD5Sum< ::fake_sensor::Detect_fruit > 
template<>
struct MD5Sum< ::fake_sensor::Detect_fruitResponse>
{
  static const char* value()
  {
    return MD5Sum< ::fake_sensor::Detect_fruit >::value();
  }
  static const char* value(const ::fake_sensor::Detect_fruitResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::fake_sensor::Detect_fruitResponse> should match 
// service_traits::DataType< ::fake_sensor::Detect_fruit > 
template<>
struct DataType< ::fake_sensor::Detect_fruitResponse>
{
  static const char* value()
  {
    return DataType< ::fake_sensor::Detect_fruit >::value();
  }
  static const char* value(const ::fake_sensor::Detect_fruitResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // FAKE_SENSOR_MESSAGE_DETECT_FRUIT_H
